#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Digitable <https://digitable.life>
# SPDX-License-Identifier: BSD-2-Clause
"""Licence gate for digitwm.

The tree holds three licences and one boundary. NOTICE writes the boundary
down; this gate is what keeps it true.

  BSD-2-Clause  our files. LICENSE, plus an SPDX header in every source
                file and script of our own.
  ISC           the files inherited from cwm. Their headers carry the
                notice; LICENSE.upstream reproduces it with all nine
                copyright lines.
  BSD-3-Clause  queue.h alone, which is sys/queue.h from OpenBSD.

The boundary is drawn by the commit that added the file, not by its header:
half our files carry no header at all, and upstream's carry no SPDX
identifier, so a header cannot be the criterion. INHERITED below is that
boundary written out; changing it is a change of fact and belongs with a
change to NOTICE.

  1. No GPL in the tree. This is the one failure here with teeth: `parse.c`
     generated by bison carries the GNU General Public License in its header,
     and it has already been committed once (see `git log` for its removal).
     It is in `.gitignore` now, but `.gitignore` does not stop `git add -f`,
     and a GPL file in this tree would relicense a window manager whose whole
     point is a permissive licence and a path back to upstream cwm.

  2. Our own source files carry `SPDX-License-Identifier: BSD-2-Clause` and a
     Digitable copyright line. The set is derived — tracked sources minus the
     inherited list — so a new file without a header fails instead of quietly
     becoming the first unmarked one. An `ISC` identifier left in one of our
     files is named as such: it is the old licence, and the file is ours.

  2b. The files of ours that carry no header — prose, the FTS models, the
     vectors, the config templates: 87 of our files, by NOTICE's own count —
     say nothing that contradicts LICENSE. Not having a header is a decision
     about where the licence is written down; it is not permission for the
     file to name someone else's licence or someone else's copyright. Check 2
     cannot reach them without demanding the header NOTICE says they must not
     have, so this one demands the opposite of a header.

  3. Inherited files carry neither `BSD-2-Clause` nor a Digitable copyright,
     and still carry the notice they arrived with. Both halves matter and
     they fail for different reasons. Writing ourselves into a header held by
     eight OpenBSD copyright holders is an assertion of authorship. Writing
     BSD-2-Clause into it is worse: it is a statement about the origin of a
     file that is mostly someone else's — `screen.c` is 135 of 442 lines
     ours, `calmwm.h` 211 of 837, and nowhere do we hold a majority.

  4. LICENSE is the verbatim BSD 2-Clause and nothing else, so that detectors
     recognise it; LICENSE.upstream keeps the ISC formula and every one of
     the nine copyright lines; NOTICE and the two plain-word pages still say
     what checks 2 and 3 assume. Checks 2 and 3 only mean something against a
     written split.

Usage:  python3 tools/check-licensing.py
Exits 1 and names every file that fails.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The files digitwm inherited from cwm, per NOTICE. Derived once from the
# commit that added each file:
#
#   git log --diff-filter=A --follow --format='%an' -- <file> | tail -1
#
# Adding a name here exempts a file from our header requirement and subjects
# it to the upstream one, so it should follow a change in NOTICE, not precede
# one.
INHERITED = {
    "Makefile", "README", "calmwm.c", "calmwm.h", "client.c", "conf.c",
    "cwm.1", "cwm.pub", "cwmrc.5", "group.c", "kbfunc.c", "menu.c",
    "migrate-config.pl", "parse.y", "queue.h", "reallocarray.c", "screen.c",
    "search.c", "strlcat.c", "strlcpy.c", "strtonum.c", "update.sh",
    "util.c", "xevents.c", "xmalloc.c", "xutil.c",
}

# Inherited files that arrived without a licence notice of their own: a
# makefile, a README, a public key, a migration script and a two-line
# updater. They are still upstream's, and still must not be marked as ours.
INHERITED_WITHOUT_NOTICE = {
    "Makefile", "README", "cwm.pub", "migrate-config.pl", "update.sh",
}

# The one inherited file under BSD-3-Clause instead of ISC: sys/queue.h from
# OpenBSD, copyright The Regents of the University of California.
INHERITED_BSD3 = "queue.h"

# `.py` is here so that this file, exempt from the GPL scan below, is still
# held to the header requirement like every other source file of ours. `.m`
# is here because macos/wsi_ax.m and tools/macos-flicker/flicker.m are
# compiled sources that the suffix list used to miss.
SOURCE_SUFFIXES = {".c", ".h", ".m", ".sh", ".mjs", ".py"}

# Scripts of ours with no suffix at all. They are executables, they are ours,
# and a suffix rule cannot see them — which is how five of them lived without
# a header until the licence changed.
OUR_SCRIPTS_WITHOUT_SUFFIX = {
    "session/bin/digitwm-dev-session",
    "session/bin/digitwm-digit.in",
    "session/bin/digitwm-lock",
    "session/bin/digitwm-panel",
    "session/bin/digitwm-session.in",
}

# The licence files themselves: checked by name in check 4, not by header.
LICENCE_FILES = {
    "LICENSE", "LICENSE.upstream", "LICENSE-EN.md", "LICENSE-RU.md", "NOTICE",
}

# Every copyright holder of the inherited code. The list is the point of
# LICENSE.upstream: the change of licence must not drop a single line.
UPSTREAM_HOLDERS = (
    "Marius Aamodt Eriksen",
    "Andy Adamson",
    "Martin Murray",
    "Ted Unangst and Todd Miller",
    "Otto Moerbeek",
    "Owain G. Ainsworth",
    "Todd C. Miller",
)

# Check 2b scans for a licence claim, so prose that *names* licences is exempt
# for the same reason it is exempt from the GPL scan below: `doc/portability.md`
# says AltTab is GPL-3.0, `LICENSE-EN.md` names all three licences, and neither
# is a claim about the file it stands in. This file is exempt because it holds
# the patterns themselves and would match its own scan.
CLAIM_SCAN_EXEMPT_SUFFIXES = {".md"}
CLAIM_SCAN_EXEMPT_NAMES = {"NOTICE", ".gitignore", "check-licensing.py"}

SPDX_LINE = re.compile(r"SPDX-License-Identifier:\s*([^\s*/#]+)")
COPYRIGHT_LINE = re.compile(r"^.{0,12}(?:Copyright|\(c\)\s+\d{4})\b.*$", re.M)

ISC_FORMULA = "Permission to use, copy, modify, and distribute this software"
BSD2_CONDITION = "Redistributions in binary form must reproduce the above"
BSD3_CONDITION = "Neither the name of the University nor the names of its"

# Prose is allowed to discuss the GPL — NOTICE explains at length why no line
# of papersway or sdorfehs is here, and .gitignore explains why generated
# parse.c must never be committed. Neither can carry licensed code; what is
# forbidden is a file that *is* under the GPL, not one that names it.
#
# This file is exempt for a sharper reason: it holds the search patterns
# themselves, so it matches its own scan by construction. Without the
# exemption the gate fails on itself the moment it is committed — which is
# exactly what happened on the first run after it was added to the tree.
GPL_SCAN_EXEMPT_SUFFIXES = {".md"}
GPL_SCAN_EXEMPT_NAMES = {"NOTICE", ".gitignore", "check-licensing.py"}

GPL_MARKERS = ("GNU General Public License", "GNU GENERAL PUBLIC LICENSE",
               "GPL-2.0", "GPL-3.0")

failures = []
passed = []


def tracked_files():
    out = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return [line for line in out.splitlines() if line]


def read(relative):
    return (ROOT / relative).read_text(encoding="utf-8", errors="replace")


def header_of(relative):
    """The first lines of a file — where an SPDX header is or is not.

    Deliberately not "the first 2 KB": this file's own docstring quotes
    `SPDX-License-Identifier: BSD-2-Clause` while explaining the rule, and a
    scan over 2 KB accepted that quotation as the header. The check then
    passed on a copy of this file whose real header had been deleted. A
    header lives at the top or it is not a header.
    """
    return "\n".join(read(relative).split("\n")[:15])


files = tracked_files()
if not files:
    print("FAIL  git ls-files returned nothing — not a checkout?", file=sys.stderr)
    sys.exit(1)

# 1. No GPL-licensed file anywhere under version control.
gpl_hits = []
for relative in files:
    path = Path(relative)
    if path.suffix in GPL_SCAN_EXEMPT_SUFFIXES or path.name in GPL_SCAN_EXEMPT_NAMES:
        continue
    try:
        text = read(relative)
    except (OSError, UnicodeError):
        continue
    for marker in GPL_MARKERS:
        if marker in text:
            gpl_hits.append(
                f"{relative}: contains `{marker}` — a copyleft file under version "
                f"control relicenses this tree and closes the path back to cwm. "
                f"If this is generated `parse.c`, it must not be committed."
            )
            break

if gpl_hits:
    failures.extend(gpl_hits)
else:
    passed.append(f"no GPL text in any of the {len(files)} tracked files")

# 2. Our own source files carry the BSD-2-Clause header.
ours = [
    f for f in files
    if f not in INHERITED and f not in LICENCE_FILES
    and (Path(f).suffix in SOURCE_SUFFIXES or f in OUR_SCRIPTS_WITHOUT_SUFFIX)
]

missing_header = []
for relative in sorted(ours):
    head = header_of(relative)
    if "SPDX-License-Identifier: BSD-2-Clause" not in head:
        if "SPDX-License-Identifier: ISC" in head:
            missing_header.append(
                f"{relative}: header still says `SPDX-License-Identifier: ISC` — "
                f"ISC is the licence of the inherited cwm files, and this file is "
                f"ours. Our code goes out under BSD-2-Clause (LICENSE, NOTICE)."
            )
        else:
            missing_header.append(
                f"{relative}: no `SPDX-License-Identifier: BSD-2-Clause` in the "
                f"opening lines (file of our own authorship — NOTICE puts new "
                f"Digitable code under BSD-2-Clause)"
            )
    elif "SPDX-FileCopyrightText:" not in head or "Digitable" not in head:
        missing_header.append(
            f"{relative}: no `SPDX-FileCopyrightText: ... Digitable` in the opening lines"
        )

if missing_header:
    failures.extend(missing_header)
else:
    passed.append(
        f"all {len(ours)} source files of our own carry SPDX BSD-2-Clause headers"
    )

# 2b. Files of ours that carry no header say nothing that contradicts LICENSE.
#
# NOTICE draws the boundary by the commit that added the file, and says outright
# that prose, the FTS models, the vectors and the config templates are *not*
# marked with a header — 87 of our 137 files carry none, and LICENSE covers them.
# That is a decision about where the licence is written down, not a decision to
# stop caring what those files say. Nothing checked it, so the 22 `.fts` and
# `.flang` models — our authorship, the specification the C is checked against,
# and in `fts/flang/output-change.flang` a policy written a second time, which
# is exactly the file another project would want to copy — could carry anyone's
# terms and pass in silence:
#
#     // Copyright (c) 2026 Some Other Corp. All rights reserved.
#     // SPDX-License-Identifier: LicenseRef-Proprietary
#
# Check 2 cannot catch that without demanding a header NOTICE says these files
# must not have. So this check demands the opposite of a header: a file of ours
# left to LICENSE must not name another licence or another copyright holder.
# Red in both directions, like check 2 — and by the same reasoning, since a
# file that says `ISC` is making the claim aeee0a0 already refuses to accept
# from a headered file.
headered = set(ours)
foreign_claim = []
for relative in files:
    path = Path(relative)
    if relative in INHERITED or relative in LICENCE_FILES or relative in headered:
        continue
    if path.suffix in CLAIM_SCAN_EXEMPT_SUFFIXES or path.name in CLAIM_SCAN_EXEMPT_NAMES:
        continue
    try:
        text = read(relative)
    except (OSError, UnicodeError):
        continue
    for identifier in SPDX_LINE.findall(text):
        if identifier != "BSD-2-Clause":
            foreign_claim.append(
                f"{relative}: says `SPDX-License-Identifier: {identifier}` — this "
                f"file is ours (NOTICE draws the boundary by the commit that "
                f"added it) and is covered by LICENSE, which is BSD-2-Clause. "
                f"Either the identifier is wrong or the file is not ours."
            )
            break
    for line in COPYRIGHT_LINE.findall(text):
        if "Digitable" not in line:
            foreign_claim.append(
                f"{relative}: carries a copyright line that is not ours — "
                f"`{line.strip()[:70]}`. A file of ours covered by LICENSE cannot "
                f"also be someone else's; if it really is theirs, it belongs in "
                f"NOTICE and in the inherited list, not here."
            )
            break

unheadered = [
    f for f in files
    if f not in INHERITED and f not in LICENCE_FILES and f not in headered
    and Path(f).suffix not in CLAIM_SCAN_EXEMPT_SUFFIXES
    and Path(f).name not in CLAIM_SCAN_EXEMPT_NAMES
]
if foreign_claim:
    failures.extend(foreign_claim)
else:
    passed.append(
        f"none of the {len(unheadered)} files of ours that LICENSE covers "
        f"without a header claims another licence or another holder"
    )

# 3. Inherited files are not relicensed and not claimed.
relicensed = []
claimed = []
lost_notice = []
for relative in sorted(INHERITED):
    if not (ROOT / relative).exists():
        failures.append(
            f"{relative}: listed as inherited in NOTICE but missing from the tree"
        )
        continue
    head = header_of(relative)
    if "BSD-2-Clause" in head:
        relicensed.append(
            f"{relative}: header says `BSD-2-Clause` — this file is inherited from "
            f"cwm and stays under its own licence. We are not entitled to "
            f"relicense it, and most of its lines are not ours."
        )
    if "Digitable" in head:
        claimed.append(
            f"{relative}: carries a Digitable copyright line — this is upstream's "
            f"file, and adding our name to it is a claim of authorship we cannot "
            f"make. Our copyright in the lines we did write there is the ninth "
            f"line of LICENSE.upstream."
        )
    if relative in INHERITED_WITHOUT_NOTICE:
        continue
    text = read(relative)
    wanted = BSD3_CONDITION if relative == INHERITED_BSD3 else ISC_FORMULA
    if wanted not in text:
        lost_notice.append(
            f"{relative}: the licence notice it arrived with is gone — keeping it "
            f"is the condition on which we hold this code"
        )

failures.extend(relicensed)
failures.extend(claimed)
failures.extend(lost_notice)
if not (relicensed or claimed or lost_notice):
    passed.append(
        f"none of the {len(INHERITED)} inherited files is relicensed, claimed "
        f"or stripped of its notice"
    )

# 4. The licence files still say what the checks above assume.
license_text = read("LICENSE")
if BSD2_CONDITION not in license_text:
    failures.append("LICENSE: the BSD 2-Clause text is gone")
elif "Digitable" not in license_text:
    failures.append("LICENSE: no Digitable copyright line, but the tree contains our code")
elif ISC_FORMULA in license_text:
    failures.append(
        "LICENSE: carries the ISC formula as well — licence detectors match "
        "against a reference text, and a second licence in the file turns a "
        "well-known one into `unrecognised`. The cwm notice belongs in "
        "LICENSE.upstream."
    )
else:
    passed.append("LICENSE is the BSD 2-Clause text of our own code and nothing else")

if not (ROOT / "LICENSE.upstream").exists():
    failures.append(
        "LICENSE.upstream: missing — the ISC notice of the inherited cwm code "
        "and its nine copyright lines have nowhere to live"
    )
else:
    upstream_text = read("LICENSE.upstream")
    if ISC_FORMULA not in upstream_text:
        failures.append("LICENSE.upstream: the ISC permission formula is gone")
    else:
        dropped = [h for h in UPSTREAM_HOLDERS if h not in upstream_text]
        if dropped:
            failures.append(
                "LICENSE.upstream: copyright holders dropped — "
                + ", ".join(dropped)
            )
        elif upstream_text.count("Copyright") != 9:
            failures.append(
                f"LICENSE.upstream: {upstream_text.count('Copyright')} copyright "
                f"lines, expected 9 — eight of upstream's and ours for the lines "
                f"we wrote in their files"
            )
        else:
            passed.append(
                "LICENSE.upstream keeps the ISC formula and all nine copyright lines"
            )

if not (ROOT / "NOTICE").exists():
    failures.append("NOTICE: missing — the split between inherited code and ours is undocumented")
else:
    notice = read("NOTICE")
    missing = [r for r in ("cwm", "OpenBSD", "ISC", "BSD-2-Clause", "BSD-3-Clause",
                           "LICENSE.upstream") if r not in notice]
    if missing:
        failures.append("NOTICE: does not mention " + ", ".join(missing))
    else:
        passed.append("NOTICE records the origin of the code and all three licences")

pages = []
for page in ("LICENSE-EN.md", "LICENSE-RU.md"):
    if not (ROOT / page).exists():
        failures.append(
            f"{page}: missing — the licence is explained in two languages, and a "
            f"page present on one surface only is a page the other language "
            f"re-derives, wrongly"
        )
        continue
    text = read(page)
    absent = [n for n in ("BSD 2-Clause", "ISC", "BSD-3-Clause") if n not in text]
    if absent:
        failures.append(f"{page}: does not name " + ", ".join(absent))
    else:
        pages.append(page)
if len(pages) == 2:
    passed.append("LICENSE-EN.md and LICENSE-RU.md both name all three licences")

for name in passed:
    print(f"ok    {name}")
for failure in failures:
    print(f"FAIL  {failure}", file=sys.stderr)

if failures:
    print(
        f"\n{len(failures)} licensing obligation(s) not met. See NOTICE.",
        file=sys.stderr,
    )
    sys.exit(1)

print(f"\n{len(passed)} checked, 0 failed.")
