#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Digitable <https://digitable.life>
# SPDX-License-Identifier: ISC
"""Licence gate for digitwm.

digitwm is a fork of cwm: 18 `.c`/`.h` files plus `parse.y` and `update.sh`
come from upstream, everything else is ours. NOTICE writes that split down and
states that new Digitable code goes out under the same ISC. The checks below
are what keeps all three of those statements true.

  1. No GPL in the tree. This is the one failure here with teeth: `parse.c`
     generated by bison carries the GNU General Public License in its header,
     and it has already been committed once (see `git log` for its removal).
     It is in `.gitignore` now, but `.gitignore` does not stop `git add -f`,
     and a GPL file in this tree would relicense a window manager whose whole
     point is a permissive licence and a path back to upstream cwm.

  2. Our own source files carry `SPDX-License-Identifier: ISC` and a Digitable
     copyright line. The set is derived — tracked sources minus the upstream
     list — so a new file without a header fails instead of quietly becoming
     the first unmarked one.

  3. Upstream's files carry no Digitable copyright. Writing ourselves into a
     header held by nine OpenBSD copyright holders is an assertion of
     authorship, and it is the error this gate exists to make impossible:
     by the time it is noticed it has already been published.

  4. LICENSE keeps the ISC formula and every copyright holder, and NOTICE
     still records where the code comes from. Checks 2 and 3 only mean
     something against a written split.

Usage:  python3 tools/check-licensing.py
Exits 1 and names every file that fails.
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Upstream's files, per NOTICE. Adding a name here exempts a file from the
# header requirement, so it should follow a change in NOTICE, not precede one.
UPSTREAM = {
    "calmwm.c", "calmwm.h", "client.c", "conf.c", "group.c", "kbfunc.c",
    "menu.c", "queue.h", "reallocarray.c", "screen.c", "search.c",
    "strlcat.c", "strlcpy.c", "strtonum.c", "util.c", "xevents.c",
    "xmalloc.c", "xutil.c",
    "parse.y", "update.sh",
}

# `.py` is here so that this file, exempt from the GPL scan above, is still
# held to the header requirement like every other source file of ours.
SOURCE_SUFFIXES = {".c", ".h", ".sh", ".mjs", ".py"}

# Prose is allowed to discuss the GPL — NOTICE explains at length why no line
# of papersway or sdorfehs is here, and .gitignore explains why generated
# parse.c must never be committed. Neither can carry licensed code; what is
# forbidden is a file that *is* under the GPL, not one that names it.
#
# This file is exempt for a sharper reason: it holds the search patterns
# themselves, so it matches its own scan by construction. Without the
# exemption the gate fails on itself the moment it is committed — which is
# exactly what happened on the first run after it was added to the tree.
GPL_SCAN_EXEMPT_SUFFIXES = {".md"}
GPL_SCAN_EXEMPT_NAMES = {"NOTICE", ".gitignore", "check-licensing.py"}

GPL_MARKERS = ("GNU General Public License", "GNU GENERAL PUBLIC LICENSE",
               "GPL-2.0", "GPL-3.0")

failures = []
passed = []


def tracked_files():
    out = subprocess.run(
        ["git", "ls-files"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return [line for line in out.splitlines() if line]


def read(relative):
    return (ROOT / relative).read_text(encoding="utf-8", errors="replace")


def header_of(relative):
    """The first lines of a file — where an SPDX header is or is not.

    Deliberately not "the first 2 KB": this file's own docstring quotes
    `SPDX-License-Identifier: ISC` while explaining the rule, and a scan
    over 2 KB accepted that quotation as the header. The check then passed
    on a copy of this file whose real header had been deleted. A header
    lives at the top or it is not a header.
    """
    return "\n".join(read(relative).split("\n")[:15])


files = tracked_files()
if not files:
    print("FAIL  git ls-files returned nothing — not a checkout?", file=sys.stderr)
    sys.exit(1)

# 1. No GPL-licensed file anywhere under version control.
gpl_hits = []
for relative in files:
    path = Path(relative)
    if path.suffix in GPL_SCAN_EXEMPT_SUFFIXES or path.name in GPL_SCAN_EXEMPT_NAMES:
        continue
    try:
        text = read(relative)
    except (OSError, UnicodeError):
        continue
    for marker in GPL_MARKERS:
        if marker in text:
            gpl_hits.append(
                f"{relative}: contains `{marker}` — a copyleft file under version "
                f"control relicenses this tree and closes the path back to cwm. "
                f"If this is generated `parse.c`, it must not be committed."
            )
            break

if gpl_hits:
    failures.extend(gpl_hits)
else:
    passed.append(f"no GPL text in any of the {len(files)} tracked files")

# 2. Our own source files carry the header.
ours = [
    f for f in files
    if f not in UPSTREAM and Path(f).suffix in SOURCE_SUFFIXES
]

missing_header = []
for relative in ours:
    head = header_of(relative)
    if "SPDX-License-Identifier: ISC" not in head:
        missing_header.append(
            f"{relative}: no `SPDX-License-Identifier: ISC` in the opening lines "
            f"(file of our own authorship — NOTICE puts new Digitable code under ISC)"
        )
    elif "SPDX-FileCopyrightText:" not in head or "Digitable" not in head:
        missing_header.append(
            f"{relative}: no `SPDX-FileCopyrightText: ... Digitable` in the opening lines"
        )

if missing_header:
    failures.extend(missing_header)
else:
    passed.append(f"all {len(ours)} source files of our own carry SPDX ISC headers")

# 3. Upstream's files are not marked as ours.
claimed = []
for relative in sorted(UPSTREAM):
    if not (ROOT / relative).exists():
        failures.append(f"{relative}: listed as upstream's in NOTICE but missing from the tree")
        continue
    head = header_of(relative)
    if "Digitable" in head:
        claimed.append(
            f"{relative}: carries a Digitable copyright line — this is upstream's "
            f"file, and adding our name to it is a claim of authorship we cannot make"
        )

if claimed:
    failures.extend(claimed)
else:
    passed.append(f"none of the {len(UPSTREAM)} upstream files claims Digitable authorship")

# 4. LICENSE and NOTICE still say what the checks above assume.
license_text = read("LICENSE")
if "Permission to use, copy, modify, and distribute this software" not in license_text:
    failures.append("LICENSE: the ISC permission formula is gone")
elif "Marius Aamodt Eriksen" not in license_text:
    failures.append("LICENSE: upstream copyright holders are gone")
elif "Digitable" not in license_text:
    failures.append("LICENSE: no Digitable copyright line, but the tree contains our code")
else:
    passed.append("LICENSE keeps the ISC formula and every copyright holder")

if not (ROOT / "NOTICE").exists():
    failures.append("NOTICE: missing — the split between upstream's code and ours is undocumented")
else:
    notice = read("NOTICE")
    for required in ("cwm", "OpenBSD", "ISC"):
        if required not in notice:
            failures.append(f"NOTICE: does not mention {required}")
            break
    else:
        passed.append("NOTICE records the origin of the code and the licence of our additions")

for name in passed:
    print(f"ok    {name}")
for failure in failures:
    print(f"FAIL  {failure}", file=sys.stderr)

if failures:
    print(
        f"\n{len(failures)} licensing obligation(s) not met. See NOTICE.",
        file=sys.stderr,
    )
    sys.exit(1)

print(f"\n{len(passed)} checked, 0 failed.")
